# -*- coding: utf-8 -*-
"""anime_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4tTYSzNpz5WXG3Ikg9wsjJiJrz9Bngt
"""

# 1. Zaroori Cheezein (Libraries)
import torch
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files
import io

# 2. AI Model Load karna (Internet se)
print("AI Model download ho raha hai... (Sirf pehli baar time lega)")
model = torch.hub.load("bryandlee/animegan2-pytorch:main", "generator", device="cuda")
face2paint = torch.hub.load("bryandlee/animegan2-pytorch:main", "face2paint", size=512, device="cuda")
model.eval()
print("Model Tayar hai! 🚀")

# 3. Aap ki Photo Upload karna
print("\nApni Tasveer (Photo) Upload karen:")
uploaded = files.upload()

# Jo file upload hui, usay uthana
filename = next(iter(uploaded))
img = Image.open(io.BytesIO(uploaded[filename])).convert("RGB")

# 4. Jadoo (Conversion to Anime)
print(f"\nProcessing '{filename}'... Please wait...")
with torch.no_grad():
    out = face2paint(model, img)

# 5. Result Dikhana
plt.figure(figsize=(12,6))

# Asal Photo
plt.subplot(1, 2, 1)
plt.title("Original Photo")
plt.imshow(img)
plt.axis("off")

# Anime Photo
plt.subplot(1, 2, 2)
plt.title("Anime Version (AI)")
plt.imshow(out)
plt.axis("off")

plt.show()

# 6. Save karke Download karna
save_name = "anime_result.jpg"
out.save(save_name)
files.download(save_name)
print(f"Mubarak ho! '{save_name}' download ho gayi hai.")